workflows:
  android-apk-release:
    name: Build Android APK (release)
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android APK (release)
        # نبني فقط للمعماريتين arm و arm64، ونتخطى tree-shake للأيقونات
        script: flutter build apk --release \
                 --no-tree-shake-icons \
                 --target-platform android-arm,android-arm64

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

