workflows:
  android-apk-release:
    name: Build Android APK (release)
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android APK (release)
        # جميع الخيارات على سطر واحد لتجنب مشكلة "\" في YAML
        script: flutter build apk --release --no-tree-shake-icons --target-platform android-arm,android-arm64

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk


