workflows:
  android-apk-release:
    name: Build Android APK (release)
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android APK (release)
        # نتخطّى tree-shake للأيقونات، ونتجاوز فحص التبعيات الخاصة بالأندرويد
        script: flutter build apk --release \
                  --no-tree-shake-icons \
                  --android-skip-build-dependency-validation

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk



