workflows:
  android-apk-release:
    name: Android APK Release
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build Android APK (release)
        script: flutter build apk --release

    artifacts:
      # مسار ملف الـAPK بعد البناء
      - build/app/outputs/flutter-apk/app-release.apk
