workflows:
  android-apk-release:
    name: Build Android APK (release)
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Precache Android artifacts
        script: flutter precache --android

      - name: Build Release APKs (split per ABI)
        # يجمع APK منفصل لكل ABI ويتجاوز أخطاء الأيقونات الثابتة
        script: flutter build apk --release --no-tree-shake-icons --split-per-abi

    artifacts:
      # يلتقط كل ملفات الـAPK الناتجة
      - build/app/outputs/flutter-apk/*.apk





